/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React, { Component } from 'react';
import { StyleSheet, Text, View, TextInput, TouchableOpacity, Alert } from 'react-native';
import RNZoomUsBridge from 'react-native-zoom-us-bridge';

const ZOOM_APP_KEY = "0pwMOPLd6vyl6a4mFo3ZMs10uy90TGKIw0c2";
const ZOOM_APP_SECRET = "j4zdEbKiLgktXxCLAh1SRIrsydFUJ2JjDaeL";
const ZOOM_APP_DOMAIN = "zoom.us";

export default class App extends Component {
  state = {
    meetingId: '',
    userName: '',

  };
  componentDidMount() {
    this.initializeZoomSDK();
  }

  initializeZoomSDK = () => {

    if (!ZOOM_APP_KEY || !ZOOM_APP_SECRET || !ZOOM_APP_DOMAIN) return false;
    // init sdk
    RNZoomUsBridge.initialize(
      ZOOM_APP_KEY,
      ZOOM_APP_SECRET,
      ZOOM_APP_DOMAIN
    ).then().catch((err) => {
      console.warn(err);
      Alert.alert('error!', err.message)
    });
  }

  joinMeeting = async () => {
    const {
      meetingId, userName
    } = this.state;

    if (!meetingId || !userName) return false;

    RNZoomUsBridge.joinMeeting(
      userName,
      meetingId
    ).then().catch((err) => {
      console.warn(err);
      Alert.alert('error!', err.message)
    });
  }
  render() {
    const {
      meetingId, userName
    } = this.state;

    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>☆RNZoomUsBridge example☆</Text>
        <TextInput
          value={meetingId}
          placeholder="Meeting ID"
          onChangeText={(text) => this.setState({meetingId: text})}
          style={styles.input}
        />
        <TextInput
          value={userName}
          placeholder="Your name"
          onChangeText={(text) => this.setState({userName: text})}
          style={styles.input}
        />
        <TouchableOpacity onPress={this.joinMeeting} style={styles.button}>
          <Text style={styles.buttonText}>
            Join Meeting
          </Text>
        </TouchableOpacity>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  input: {
    width: 200,
    padding: 10,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: 'grey',
    margin: 3,
  },
  button: {
    width: 200,
    padding: 10,
    borderRadius: 5,
    backgroundColor: 'salmon',
    alignItems: 'center',
    justifyContent: 'center',
    margin: 3,
  },
  buttonText: {
    color: 'white',
  }
});
